services:
  frontend:
    build:
      context: .
    ports:
      - 3000:3000
    depends_on:
      - server

  server:
    container_name: server
    restart: always
    build:
      context: ./backend
    ports:
      - 5000:5000
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017/workout?authSource=admin

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin

volumes:
  mongo_data:
