export const MAKE_REQUEST = 'MAKE_REQUEST';
export const FAIL_REQUEST = 'FAIL_REQUEST';
export const GET_BIOMETRIA_LIST='GET_BIOMETRIA_LIST';
export const UPDATE_BIOMETRIA = 'UPDATE_BIOMETRIA';
export const GET_BIOMETRIA_ITEM = 'GET_BIOMETRIA_ITEM';