export const MAKE_REQUEST_EXERCICIO = 'MAKE_REQUEST_EXERCICIO';
export const FAIL_REQUEST_EXERCICIO = 'FAIL_REQUEST_EXERCICIO';
export const GET_EXERCICIO_LIST = 'GET_EXERCICIO_LIST';
export const SET_EXERCICIO_LIST = 'SET_EXERCICIO_LIST';
